//! Test root for `zig build test`. Zig only collects `test` blocks from files the test root references, so
//! every test-bearing file in src/ is listed here explicitly — a new module's tests do NOT run in CI until
//! it is added to this list.

test {
    _ = @import("auth/api_keys.zig"); // nlk_ key minting, hash-only retention, exact-match verify, revoke
    _ = @import("main.zig"); // the ROUTER audit: every admin path admin-gated, nothing else open by accident
    _ = @import("admin/admin_service.zig"); // god-mode routes: the auth sweep + its exhaustiveness guard
    _ = @import("auth/auth_api.zig"); // the front door: closed registration, login throttle, gated key routes
    _ = @import("auth/auth_core.zig"); // tool_grants persistence + the admin-email predicate
    _ = @import("auth/login_guard.zig"); // per-IP fail window, lockout expiry, per-address isolation
    _ = @import("cli.zig");
    _ = @import("cli/hub.zig"); // broadcast body escaping: a pasted CRLF must not break the JSON
    _ = @import("config/cf_oauth.zig");
    _ = @import("config/cf_r2.zig"); // the R2 backup: gated routes, object-key charset, state defaults
    _ = @import("config/cf_tunnel.zig"); // the tunnel: gated routes, token-free state, the permission explanation
    _ = @import("config/key_vault.zig"); // registered DIRECTLY: reaching the root through another
    // module is not proof of collection — lazy analysis silently dropped desk/assets.zig's tests
    // the same way (ledger 0029).
    _ = @import("config/keys_api.zig"); // every vault route is gated (handler tests via http.testApp)
    _ = @import("config/server_config.zig");
    _ = @import("config/lan.zig");
    _ = @import("config/local_models.zig"); // NOT collected before this line: main.zig imports it, lazy analysis never reached it
    _ = @import("worker/ocr.zig"); // OCR shim write-once + degradation; the PS1 flag/source agreement audit
    _ = @import("gateway/http.zig"); // jstr escaping (no forged structure) + appendFile's monotonic growth
    _ = @import("obs/audit_log.zig"); // tamper-evidence: hash chain verify, escaping round trip, doctored-file detection
    _ = @import("worker/agi.zig");
    _ = @import("worker/hashline.zig"); // hash-anchored atomic line edits (tag dialect of edit_file)
    _ = @import("worker/browser/cdp.zig"); // JSON-RPC demux + RFC-6455 framing, no socket needed
    _ = @import("worker/browser/host.zig"); // the discovery file: where a tool call finds the browser daemon
    _ = @import("worker/browser/manager.zig");
    _ = @import("worker/browser/session.zig"); // the CDP/extension driver: click-effect fingerprint diff
    _ = @import("worker/browser/ext.zig"); // the extension relay: command lifecycle + honest liveness
    _ = @import("worker/browser/ext_api.zig"); // who may pair, who may relay
    _ = @import("worker/pixelrag.zig"); // doc-id safety, fact sanitising, query→tile scoring
    _ = @import("worker/bufedit.zig");
    _ = @import("worker/builtin.zig"); // built-in engine facade: sentinel resolution + weights-store election
    _ = @import("worker/builtin_endpoint.zig"); // the engine's loopback dialect surface, tested on a mock engine
    _ = @import("worker/modelpull.zig"); // weights downloader: repo resolve, resume, sha verify — via fakehttp
    _ = @import("worker/chat/context.zig");
    _ = @import("worker/chat/engine.zig");
    _ = @import("worker/chat/paths.zig");
    _ = @import("worker/chat/plan.zig");
    _ = @import("worker/chat/service.zig");
    _ = @import("worker/chat/sync.zig");
    _ = @import("worker/chat/toolperf.zig");
    _ = @import("worker/chat/tools.zig"); // the shared tool endpoint: the admin-only capability gate
    _ = @import("worker/chat/trio_routing_test.zig"); // label->role routing guard (reads engine.zig as source)
    _ = @import("worker/chat/workspace.zig"); // prompt workspace: fixed-order scored admission + decision log
    _ = @import("plan/billing_seam.zig"); // the upgrade pitch advertises what the pro row actually grants
    _ = @import("plan/entitlements.zig"); // the plan -> caps wall
    _ = @import("plan/neurons.zig"); // the metered-AI spend ledger
    _ = @import("worker/control/fanout.zig"); // whose events you may read, and the poll cursor clients get
    _ = @import("worker/deploy/service.zig"); // auth sweep + guard, cross-tenant refusal, path traversal
    _ = @import("worker/control/supervisor.zig");
    _ = @import("worker/control/writer.zig"); // control-bus wire shape; escaping blocks op smuggling
    _ = @import("worker/commons.zig"); // swarm bus + task board (bus delivery, board fold, escape traps)
    _ = @import("worker/browser/launch.zig"); // direct, per ledger 0029
    _ = @import("worker/browser/util.zig");
    _ = @import("worker/cftools.zig"); // the cf_ belt: path/URL jails, the no-account refusal, schema↔dispatch agreement
    _ = @import("worker/crawl.zig");
    _ = @import("worker/dataset.zig"); // training-set capture: the sft/raw/tools record shapes + the marker switch
    _ = @import("worker/deps.zig");
    _ = @import("worker/evcursor.zig"); // events.jsonl poll cursor: probe sentinel, page cap, catch-up walk
    _ = @import("worker/gemma4.zig"); // gemma4 wire format: byte-exact vs the model's own chat template
    _ = @import("worker/httpc.zig");
    _ = @import("worker/hyperspace.zig");
    _ = @import("worker/lineage.zig"); // cross-run persistent swarm memory (stable neuron-db identity)
    _ = @import("worker/llm.zig");
    _ = @import("worker/locs/atlas.zig");
    _ = @import("worker/mcp/client.zig"); // JSON-RPC demux: right id only, errors/close -> null
    _ = @import("worker/mcp/discovery.zig");
    _ = @import("worker/metrics.zig");
    _ = @import("worker/neuron/client.zig"); // the datastore bridge: upsert semantics + who errors vs stays silent
    _ = @import("modelcfg"); // its own module now (see build.zig); a path import would double-own the file
    _ = @import("plug/lua.zig"); // embedded Lua sandbox: whitelist, budgets, json bridge
    _ = @import("plug/theme.zig"); // shared theme workspace: parse/seed/scan/json
    _ = @import("plug/plugins.zig"); // plugin registry: manifests, hooks (policy/prompt/tool), MCP bridge
    _ = @import("worker/net.zig"); // cached offline probe: the hosted fast-fail behind "Internet is offline"
    _ = @import("worker/continuity.zig"); // durable resume anchors: a cut unit of work continues, not restarts
    _ = @import("worker/oscillation.zig");
    _ = @import("worker/ragingest.zig"); // local-file → neuron-db distillation (offline "absorb the book")
    _ = @import("worker/ragmirror.zig"); // local knowledge-pack mirror: url→disk resolve + atlas extension
    _ = @import("worker/rate.zig");
    _ = @import("worker/recipes.zig"); // parse/substitute/validate — the granted-recipe trust boundary
    _ = @import("worker/rerank.zig");
    _ = @import("worker/rsi.zig");
    _ = @import("worker/run.zig");
    _ = @import("worker/sched.zig");
    _ = @import("worker/toolchain.zig"); // dependency bootstrap + manifest-derived acceptance rows
    _ = @import("worker/tools.zig");
    _ = @import("worker/vcs.zig");
    _ = @import("worker/writer.zig"); // grounding floor: numbered sources + citation resolution (pure parts)
}
